/**
 * Text widget metadata for platform UI.
 */

import { defineMeta } from '../../../../schema/meta'
import type { TextProps } from './types'

export const meta = defineMeta<TextProps>({
  id: 'Text',
  name: 'Text',
  description: 'Displays text content with semantic HTML elements',
  category: 'primitive',
  icon: 'text',
  tags: ['content', 'typography', 'heading', 'paragraph'],
  component: true,

  settings: {
    content: {
      type: 'textarea',
      label: 'Content',
      default: '',
      description: 'Text content to display',
      validation: { required: true, maxLength: 50000 },
      bindable: true,
    },
    as: {
      type: 'select',
      label: 'Scale',
      default: 'body',
      description: 'Type scale level (maps to theme typography)',
      choices: [
        { value: 'display', label: 'Display — Brand Statement' },
        { value: 'h1', label: 'H1 — Page Heading' },
        { value: 'h2', label: 'H2 — Section Heading' },
        { value: 'h3', label: 'H3 — Sub-heading' },
        { value: 'body', label: 'Body' },
        { value: 'small', label: 'Small — Caption & Metadata' },
        { value: 'xs', label: 'Extra Small — Fine Print' },
      ],
    },
    variant: {
      type: 'text',
      label: 'Variant',
      default: '',
      description: 'Semantic variant for CSS styling (data-variant attribute)',
      validation: { maxLength: 100 },
      advanced: true,
      hidden: true,
    },
    color: {
      type: 'select',
      label: 'Color',
      default: 'inherit',
      description: 'Text color from theme palette',
      choices: [
        { value: 'inherit', label: 'Inherit' },
        { value: 'primary', label: 'Primary' },
        { value: 'secondary', label: 'Secondary' },
        { value: 'accent', label: 'Accent' },
        { value: 'interaction', label: 'Interaction' },
      ],
    },
    textAlign: {
      type: 'select',
      label: 'Alignment',
      default: '',
      description: 'Text alignment',
      choices: [
        { value: '', label: 'Inherit' },
        { value: 'left', label: 'Left' },
        { value: 'center', label: 'Center' },
        { value: 'right', label: 'Right' },
        { value: 'justify', label: 'Justify' },
      ],
    },
    textTransform: {
      type: 'select',
      label: 'Transform',
      default: '',
      description: 'Text transform (uppercase, lowercase, capitalize)',
      choices: [
        { value: '', label: 'None' },
        { value: 'uppercase', label: 'Uppercase' },
        { value: 'lowercase', label: 'Lowercase' },
        { value: 'capitalize', label: 'Capitalize' },
      ],
    },
    fontWeight: {
      type: 'select',
      label: 'Weight',
      default: '',
      description: 'Font weight override (inherits from theme by default)',
      choices: [
        { value: '', label: 'Inherit' },
        { value: '300', label: 'Light' },
        { value: '400', label: 'Normal' },
        { value: '500', label: 'Medium' },
        { value: '600', label: 'Semibold' },
        { value: '700', label: 'Bold' },
        { value: '800', label: 'Extrabold' },
        { value: '900', label: 'Black' },
      ],
    },
    blendMode: {
      type: 'select',
      label: 'Blend Mode',
      default: '',
      description: 'CSS mix-blend-mode for visual effects',
      choices: [
        { value: '', label: 'Normal' },
        { value: 'multiply', label: 'Multiply' },
        { value: 'screen', label: 'Screen' },
        { value: 'overlay', label: 'Overlay' },
        { value: 'difference', label: 'Difference' },
        { value: 'exclusion', label: 'Exclusion' },
        { value: 'color-dodge', label: 'Color Dodge' },
        { value: 'color-burn', label: 'Color Burn' },
      ],
    },
    letterSpacing: {
      type: 'text',
      label: 'Letter Spacing',
      default: '',
      description: 'Letter spacing override (e.g. -0.02em, 0.05em)',
      group: 'Typography',
      advanced: true,
      validation: { maxLength: 20 },
    },
    lineHeight: {
      type: 'text',
      label: 'Line Height',
      default: '',
      description: 'Line height override (e.g. 1.2, 1.5)',
      group: 'Typography',
      advanced: true,
      validation: { maxLength: 20 },
    },
    html: {
      type: 'toggle',
      label: 'Render as HTML',
      default: false,
      description: 'Render content as HTML (enables inline links, etc.)',
      advanced: true,
    },
    linkHoverStyle: {
      type: 'select',
      label: 'Link Hover Style',
      default: 'hover-underline',
      description: 'How inline links behave on hover (only applies when HTML mode is on)',
      choices: [
        { value: 'none', label: 'None' },
        { value: 'underline', label: 'Always Underlined' },
        { value: 'hover-underline', label: 'Underline on Hover' },
      ],
    },
  },
})
